services:

  database:
    image: postgres:14.11-alpine
    container_name: secret-db
    hostname: postgres
    restart: always
    env_file:
      - .env
    expose:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  # BackEnd
  backend:
    build:
      context: .
    container_name: secret-backend
    volumes:
      - .:/backend
    ports:
      - '8000:8000'
    env_file:
      - .env
    restart: always
    depends_on:
      database:
        condition: service_healthy


volumes:
  db:
